### ISSUE TITLE
Error: Please select an identifier to rename.

### ISSUE THREAD

**Issue by cocodrino** [microamp/godoctor.el#9] opened 2016-11-13 17:49 UTC
Hi..I'm getting this error when I run the rename tool, I'm using spacemacs so I'm not sure if it'd be the problem...I've put the cursor over the word than I want to change, selected it, copy it, it doesnt work in any situation..thanks

```lisp

Defaulting to file scope /home/yo/Documentos/proyectos/go/basicSocket/main.go for refactoring (provide an explicit scope to change this)
main.go:44:24: Error: Please select an identifier to rename. (Selected node: *ast.FuncDecl)
```

**Comment by microamp** [comment] 2016-11-13 21:18
Thanks for the report. 

Are you able to run `godoctor` directly from your command-line and see if you can reproduce it? I'm not sure if the issue is specific to the Emacs package or the `godoctor` command itself.

``` bash
godoctor -help
```

IIRC, the command to run is 

``` bash
godoctor -file <your_file_name.go> -pos <offset,length> rename <new_symbol> 
```

e.g.

``` bash
godoctor -file your_go_file.go -pos 44,4 rename num
```

where `offset` is the value of `(point)` and `length` is the length of the symbol (e.g. `five`, hence `4`).

Otherwise, please consider posting your file as a gist. I will have a look at it. 

Thanks!

**Comment by cocodrino** [comment] 2016-11-20 23:08
hi..thanks for the reply...

when I run `godoctor-help` I get this

``` bash

godoctor -help
Run 'godoctor -help' for more information.
Go Doctor 0.3 (Beta) - Go source code refactoring tool.
Usage: godoctor [<flag> ...] <refactoring> [<args> ...]

Each <flag> must be one of the following:
    -complete Output entire modified source files instead of displaying a diff
    -doc      Output documentation (install, user, man, or vim) and exit
    -file     Filename containing an element to refactor (default: stdin)
    -json     Accept commands in OpenRefactory JSON protocol format
    -list     List all refactorings and exit
    -pos      Position of a syntax element to refactor (default: entire file)
    -scope    Package name(s), or source file containing a program entrypoint
    -v        Verbose: list affected files
    -vv       Very verbose: list individual edits (implies -v)
    -w        Modify source files on disk (write) instead of displaying a diff


The <refactoring> argument determines the refactoring to perform:
    rename          Changes the name of an identifier
    extract         Extracts statements to a new function/method
    toggle          Toggles between a var declaration and := statement
    godoc           Adds stub GoDoc comments where they are missing

The <args> following the refactoring name vary depending on the refactoring.

To display usage information for a particular refactoring, such as rename, use:
    %% godoctor rename

For complete usage information, see the user manual: http://gorefactor.org/doc.html


```

I test it using this code

``` go

package main

import (
    "github.com/goadesign/goa"
    "goaprueba/app"
    "strconv"
)

// OperadorController implements the operador resource.
type OperadorController struct {
    *goa.Controller
}

// NewOperadorController creates a operador controller.
func NewOperadorController(service *goa.Service) *OperadorController {
    return &OperadorController{Controller: service.NewController("OperadorController")}
}

// Add runs the add action.
func (c *OperadorController) Add(ctx *app.AddOperadorContext) error {
    sum := ctx.Left + *ctx.Right
    return ctx.OK([]byte(strconv.Itoa(sum)))
}



```

when I try to change ctx for ctx2 seems works ok, although this just show the info about changes and don't make any rename...

``` emacs

godoctor -file operador.go -pos 468,3  rename ctx2                                                                                             3 
Defaulting to package scope goaprueba for refactoring (provide an explicit scope to change this)
diff -u operador.go operador.go
--- operador.go
+++ operador.go
@@ -17,7 +17,7 @@
 }

 // Add runs the add action.
-func (c *OperadorController) Add(ctx *app.AddOperadorContext) error {
-   sum := ctx.Left + *ctx.Right
-   return ctx.OK([]byte(strconv.Itoa(sum)))
+func (c *OperadorController) Add(ctx2 *app.AddOperadorContext) error {
+   sum := ctx2.Left + *ctx2.Right
+   return ctx2.OK([]byte(strconv.Itoa(sum)))
 }



```

now..trying on emacs works the first time, I place over ctx and run rename, I rename ctx->ctx3 and works great, but I change the buffer and try to change other variable and it doesnt works, then I return to this file and tried change ctx3 for ctx again...this show the error

``` emacs
Defaulting to package scope goaprueba for refactoring (provide an explicit scope to change this)
operador.go:20:39: Error: Please select an identifier to rename. (Selected node: *ast.StarExpr)


```

seems like a small bug, It's weird because when I run rename, the extension is correctly capturing the word under the cursor, look the image

![asds](https://cloud.githubusercontent.com/assets/616412/20467010/47834126-af54-11e6-847d-8924622e5cdc.png)

I change New name: ctx4 for ctx but then emacs display the error

``` emacs


Defaulting to package scope goaprueba for refactoring (provide an explicit scope to change this)
operador.go:20:37: Error: Please select an identifier to rename. (Selected node: *ast.Field)

```

plase let me know if you need more details, I'm using spacemacs, which use evil-mode inside, not sure if the problem could be this, although I can tell you than the extension is capturing the word under the cursor correctly..

thanks!

**Comment by microamp** [comment] 2016-11-23 01:00
Hi, thanks for the detailed report.

> when I try to change ctx for ctx2 seems works ok, although this just show the info about changes and don't make any rename...

In my first reply, I left out the parameter, `-w`, by mistake. Without the param specified, the command does a dry run. In other words, it would only show you the diff without actually writing the changes to the file.

> now..trying on emacs works the first time, I place over ctx and run rename, I rename ctx->ctx3 and works great, but I change the buffer and try to change other variable and it doesnt works, then I return to this file and tried change ctx3 for ctx again...this show the error

Let me take a closer look at it. My hunch is that it's to do with `godoctor` itself, but I cannot be certain until further verification. Thanks for your patience.

**Comment by microamp** [comment] 2016-11-23 01:01
By the way, I'm a Spacemacs user too, but I doubt that's what's causing this issue.

**Comment by grafov** [comment] 2016-11-27 20:29
It looks like the scope problem with go-guru. I think emacs mode need ability explicitly set scope of the project like go-guru does (see `go-guru-set-scope`) and call `godoctor` with -scope parameter.

**Comment by microamp** [comment] 2016-12-05 09:49
`godoctor.el` is now using an alternative format for its `pos` argument as explained https://github.com/microamp/godoctor.el/pull/12 which appears to be more stable. @cocodrino mind trying out the latest version?

**Comment by cocodrino** [comment] 2016-12-18 00:24
hi guys, sorry for not answer before, the problem persists even with the latest version...I installed it using melpa, is the melpa repository updated?

**Comment by microamp** [comment] 2016-12-21 11:10
Yes, the one on MELPA should be the most up-to-date version. That's a shame. Would you be able to post a self-contained [gist](https://gist.github.com/) so that I can easily try out locally at my end?

**Comment by birdayz** [comment] 2018-07-08 13:38
Still got that problem with the latest codebase. apparently, always the full length of the variable/type/... is passed (offset:length is passed as -pos). even if your cursor is somewhere in the middle of the word.
This leads to godoctor not getting hold of the name directly, instead it gets a reference to the whole assignment etc, and it won't work.
solution: pass correct length to godoctor.
any1 wants to work on this? maybe i can fix it, but as i'm no lisp programmer i would need to invest more time than i want into this (apparently trivial) issue.
in essence, we just have to compute the remaining length of the word under the cursor.. but no idea how to the get information where the cursor is and the pos where the word ends.

**Comment by microamp** [comment] 2018-07-10 03:56
Hi @birdayz thanks for the comment. I'll verify the cause of the issue as you described first, then will fix it afterwards. I no longer use Go on my day job, so I'll have to find time to work on this. Thanks for the patience in advance.

**Comment by microamp** [comment] 2018-07-10 09:44
@birdayz 

I pushed some fix for the symbol-at-point issue mentioned above to a separate branch. https://github.com/microamp/godoctor.el/commit/63f87de Feel free to test it locally and provide feedback. I'll update the `master` branch in a day or two.

1. Clone the project locally
2. Check out to the branch, `rename-symbol-at-point`
2. If you are using `use-package`, try a snippet like below
```
(use-package godoctor
  :load-path "/your/local/dir/to/godoctor.el"
  :after go-mode)
```
3. Test by running `M-x godoctor-rename`

**Comment by microamp** [comment] 2018-07-10 22:00
I did some additional testing and decided to merge it into `master` afterwards. ~MELPA hasn't picked it up yet, but hopefully soon. Please check when the latest version becomes available.~ Thanks!

Edit: Updated on MELPA now. https://melpa.org/#/godoctor

**Comment by birdayz** [comment] 2018-07-11 07:10
Perfect! It works now even if the cursor is "inside" a name. Tested it with a variable in an assignment and a function name. Thanks!

**Comment by microamp** [comment] 2018-07-11 21:15
@birdayz 

Awsome. Thanks for verifying the fix. I'm not sure if what @cocodrino had reported is exactly same as yours, but `godoctor-rename` should work more reliably nonetheless. I get to close this ticket finally. Thanks guys.

**Closed as completed by microamp** 2018-07-11 21:15 UTC
